"""add allow_multiple_buyins

Revision ID: 7e9e0380aab8
Revises: 003
Create Date: 2026-04-04 09:40:44.120916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e9e0380aab8'
down_revision: Union[str, Sequence[str], None] = '003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chip_denominations', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('chip_denominations', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.add_column('clubs', sa.Column('allow_multiple_buyins', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.alter_column('clubs', 'default_rake_buyin',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('clubs', 'default_rake_rebuy',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('payments_pix', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_index('ix_players_club_phone', table_name='players')
    op.alter_column('session_players', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('session_players', 'total_chips_in',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('session_players', 'total_chips_out',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sessions', 'allow_rebuys',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('sessions', 'rake_buyin',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('sessions', 'rake_rebuy',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('sessions', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('transactions', 'rake_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('transactions', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('transactions', 'rake_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('sessions', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('sessions', 'rake_rebuy',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('sessions', 'rake_buyin',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('sessions', 'allow_rebuys',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('session_players', 'total_chips_out',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('session_players', 'total_chips_in',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('session_players', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.create_index('ix_players_club_phone', 'players', ['club_id', 'phone'], unique=False)
    op.alter_column('payments_pix', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('clubs', 'default_rake_rebuy',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('clubs', 'default_rake_buyin',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.drop_column('clubs', 'allow_multiple_buyins')
    op.alter_column('chip_denominations', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('chip_denominations', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    # ### end Alembic commands ###
