"""add_table_limit_and_kits_to_session

Revision ID: c9ebe7f2fe11
Revises: 7e9e0380aab8
Create Date: 2026-04-04 10:40:13.803186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c9ebe7f2fe11'
down_revision: Union[str, Sequence[str], None] = '7e9e0380aab8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('table_limit', sa.Integer(), nullable=True))
    op.add_column('sessions', sa.Column('buyin_kit', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('sessions', sa.Column('rebuy_kit', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'rebuy_kit')
    op.drop_column('sessions', 'buyin_kit')
    op.drop_column('sessions', 'table_limit')
    # ### end Alembic commands ###
