/**
 * All strings in pt-BR.
 */
export const pt = {
  // Status labels
  status: {
    waiting_payment: "Aguardando pagamento",
    active: "Ativo",
    cashed_out: "Encerrado",
  },

  // Join page
  join: {
    title: "Entrar na Mesa",
    nameLabel: "Nome",
    namePlaceholder: "Seu nome",
    phoneLabel: "Telefone",
    phonePlaceholder: "(11) 99999-9999",
    submit: "Entrar na Mesa",
    welcomeBack: (name: string) => `Bem-vindo de volta, ${name}!`,
    sessionClosed: "Esta sessão foi encerrada",
    sessionNotFound: "Sessão não encontrada",
    phoneError: "Telefone deve ter 10 ou 11 dígitos (com DDD)",
    nameError: "Nome deve ter pelo menos 2 caracteres",
  },

  // Player page
  player: {
    chipsIn: "Buy-in",
    rebuys: "Rebuys",
    rebuyButton: "Rebuy",
    pixTitle: "Pague com Pix",
    copyCode: "Copiar código",
    copied: "Copiado!",
    waitingPayment: "Aguardando confirmação do pagamento...",
    paymentExpired: "Pagamento expirado",
    generateNew: "Gerar novo QR",
    sessionClosed: "Sessão encerrada. Obrigado por jogar!",
    invalidLink: "Link inválido. Escaneie o QR code novamente.",
    transactionHistory: "Transações",
    verifyChips: "Verificar minhas fichas",
    totalChipsCount: "Total de Fichas",
    paymentUnavailable: "Serviço de pagamento indisponível. Tente novamente.",
    tabSession: "Sessão",
    tabCashKing: "Rei do Cash",
    tabHistory: "Histórico",
    totalInvested: "Investido",
    totalCashout: "Cashout",
    netResult: "Resultado",
    noHistory: "Nenhuma sessão anterior",
    yourPosition: "Sua Posição",
    notRanked: "Sem pontuação ainda",
    staticPixTitle: "Pague com Pix",
    staticPixInstructions: "Abra seu app do banco e faca um Pix para a chave abaixo no valor indicado.",
    staticPixWaiting: "Aguardando confirmacao do administrador...",
    staticPixKey: "Chave Pix",
  },

  // TV Lobby
  tv: {
    scanToJoin: "Escaneie para entrar",
    players: "Jogadores",
    noPlayers: "Aguardando jogadores...",
    reconnecting: "Reconectando...",
  },

  // Transaction types
  txType: {
    buy_in: "Buy-in",
    rebuy: "Rebuy",
    cash_out: "Cashout",
  },

  // Payment methods
  paymentMethod: {
    pix: "Pix",
    cash: "Dinheiro",
  },

  // Admin sections
  admin: {
    login: {
      title: "Administração do Sistema",
      phoneLabel: "Telefone",
      phonePlaceholder: "Seu telefone cadastrado",
      codeLabel: "Código Secreto",
      codePlaceholder: "Sua senha de admin",
      submit: "Entrar",
      loggingIn: "Entrando...",
    },
    owner: {
      sectionTitle: "Dono do Clube (opcional)",
      sectionDesc: "Cadastre um dono para que ele faça login e gerencie o clube.",
      nameLabel: "Nome do Dono",
      emailLabel: "E-mail",
      phoneLabel: "Telefone",
      passwordLabel: "Senha Inicial",
    },
    theme: {
      title: "Aparência",
      logoUrl: "URL do Logo",
      logoPlaceholder: "https://exemplo.com/logo.png",
      primaryColor: "Cor Primária",
      accentColor: "Cor de Destaque",
      bgColor: "Cor de Fundo",
      textColor: "Cor do Texto",
      bgImageUrl: "URL da Imagem de Fundo",
      fontFamily: "Fonte",
      tvLayout: "Layout da TV",
      layoutClassic: "Clássico",
      layoutCards: "Cartões",
      layoutMinimal: "Minimalista",
      preview: "Pré-visualização",
    },
    clubs: {
      title: "Seus Clubes",
      newClub: "Novo Clube",
      noClubs: "Você ainda não possui clubes.",
      settingsTitle: "Configurações do Clube",
      saveSettings: "Salvar Configurações",
      saving: "Salvando...",
      deleteClub: "Excluir Clube",
    },
    dashboard: {
      title: "Painel da Sessão",
      newSession: "Nova Sessão",
      closeSession: "Encerrar Sessão",
      tvLobby: "Lobby TV",
      noOpenSession: "Nenhuma sessão aberta.",
      createSessionTitle: "Abrir Nova Sessão",
      createSessionSubmit: "Abrir Sessão",
      creating: "Abrindo...",
      sessionLabel: "Nome da Sessão",
      blindsLabel: "Valor do Blind (R$)",
      buyinLabel: "Buy-in (R$)",
      rebuyLabel: "Rebuy (R$)",
      tableLimit: "Limite de Jogadores",
      allowRebuys: "Permitir Rebuys",
      summary: {
        players: "Jogadores",
        chipsIn: "Fichas In",
        chipsOut: "Fichas Out",
        discrepancy: "Discrepância",
        rake: "Rake Total",
      },
      playersTable: {
        name: "Nome",
        phone: "Telefone",
        status: "Status",
        chipsIn: "Fichas In",
        chipsOut: "Fichas Out",
        actions: "Ações",
        noPlayers: "Nenhum jogador na mesa ainda.",
      },
      actions: {
        addPlayer: "Adicionar Jogador",
        verifyPayment: "Verificar",
        markCash: "Pago (Dinheiro)",
        cashout: "Cashout",
        history: "Histórico",
      },
    },
    playerHistory: {
      title: "Histórico do Jogador",
      aggregate: {
        totalSessions: "Sessões",
        totalBuyin: "Total Investido",
        totalCashout: "Total Retirado",
        netResult: "Saldo Geral",
      },
      table: {
        session: "Sessão",
        date: "Data",
        buyin: "Buy-in",
        cashout: "Cashout",
        net: "Net",
      }
    },
    settings: {
      allowMultipleBuyins: "Permitir múltiplos buy-ins ao adicionar jogador",
      chipInventory: "Inventário de Fichas",
      addChip: "Adicionar Denominação",
      chipLabel: "Etiqueta",
      chipValue: "Valor",
      chipQty: "Qtd. Total",
      chipActive: "Ativa",
      rakeDefaults: "Padrões de Rake",
      rakeBuyin: "Rake por Buy-in (R$)",
      rakeRebuy: "Rake por Rebuy (R$)",
      paymentConfig: "Pagamento",
      paymentModeStaticPix: "Pix Estatico",
      paymentModeStaticPixDesc: "Jogadores pagam manualmente via Pix. Voce confirma o recebimento.",
      paymentModeMP: "Mercado Pago",
      paymentModeMPDesc: "QR Code dinamico com confirmacao automatica.",
      pixKeyLabel: "Chave Pix do Clube",
      pixKeyPlaceholder: "CPF, e-mail, telefone ou chave aleatoria",
      mpAccessTokenLabel: "Access Token",
      mpWebhookSecretLabel: "Webhook Secret",
      mpFeeWarning: "O Mercado Pago cobra taxas sobre cada transacao. Para buy-ins pequenos (ex: R$20), isso pode representar um custo significativo para o clube.",
      mpCredentialsConfigured: "Credenciais configuradas",
    },
    modals: {
      addPlayerTitle: "Adicionar Jogador Manualmente",
      cashoutTitle: "Encerrar Participação (Cashout)",
      closeSessionConfirm: "Deseja encerrar esta sessão?",
      closeSessionWarning: "Existem jogadores que ainda não realizaram o cashout.",
      reconciliationTitle: "Resumo de Fechamento",
    }
  },

  // Cash King
  cashKing: {
    title: "Rei do Cash",
    enableLabel: "Rei do Cash (ranking mensal)",
    croupierHoursLabel: "Horas como crupiê",
    pointsEarned: "Pontos Rei do Cash",
    leaderboard: "Ranking Mensal",
    noEntries: "Nenhum jogador pontuou neste mês.",
    position: "#",
    player: "Jogador",
    totalPts: "Pontos",
    sessions: "Sessões",
    attendance: "Presença",
    hours: "Horas",
    croupier: "Crupiê",
    profit: "Lucro",
    adjustment: "Ajuste",
    total: "Total",
    editScore: "Editar Pontuação",
    addPlayer: "Adicionar ao Ranking",
    addPlayerDesc: "Adicionar jogador manualmente ao ranking",
    searchPlayer: "Buscar jogador...",
    descriptionLabel: "Descrição (opcional)",
    descriptionPlaceholder: "Ex: Bônus evento especial",
    noPlayersFound: "Nenhum jogador encontrado",
    save: "Salvar",
    cancel: "Cancelar",
    delete: "Remover",
    deleteConfirm: "Remover esta entrada do ranking?",
    manual: "Manual",
  },

  // Owner sections
  owner: {
    login: {
      title: "Painel do Clube",
      emailLabel: "E-mail",
      emailPlaceholder: "seu@email.com",
      passwordLabel: "Senha",
      passwordPlaceholder: "Sua senha",
      submit: "Entrar",
      loggingIn: "Entrando...",
    },
    dashboard: {
      loading: "Carregando seu clube...",
      noClub: "Nenhum clube vinculado à sua conta. Entre em contato com o administrador.",
      logout: "Sair",
    },
    register: {
      title: "Crie seu Clube",
      subtitle: "Comece a gerenciar suas mesas de poker",
      nameLabel: "Seu nome",
      namePlaceholder: "João Silva",
      emailLabel: "E-mail",
      emailPlaceholder: "seu@email.com",
      phoneLabel: "Telefone",
      phonePlaceholder: "(11) 99999-9999",
      passwordLabel: "Senha",
      passwordPlaceholder: "Mínimo 6 caracteres",
      clubNameLabel: "Nome do clube",
      clubNamePlaceholder: "Poker Club São Paulo",
      clubSlugLabel: "URL do clube",
      clubSlugPlaceholder: "meu-clube",
      clubSlugHint: "Apenas letras minúsculas, números e hífens",
      submit: "Criar conta",
      creating: "Criando...",
      hasAccount: "Já tem conta?",
      loginLink: "Entrar",
    },
  },

  // General
  loading: "Carregando...",
  error: "Ocorreu um erro. Tente novamente.",
  currency: (value: number) =>
    `R$ ${value.toLocaleString("pt-BR", { minimumFractionDigits: 2 })}`,
};
